### ISSUE TITLE
Log rotation by file size

### ISSUE THREAD

**Issue by akinsey** [hapijs/good-file#53]
I was wondering if there were any future plans to support rotating log files once the log file reaches a predefined file size?

Thanks!

**Comment by arb** [comment]
No it is unlikely. It was a feature previously, but never worked right and ended up adding a lot of code complexity. [This issue](https://github.com/hapijs/good-file/issues/39) talks about the removal of this option. A suggestion is to use some other process to archive off log files once they grow too large.

It's also worth pointing out that Bunyan, a project that influenced this plugin, does not offer this feature either.

**Comment by lloydbenson** [comment]
To add, you can use logrotate to do this kind of activity which is I think
what most folks do.
