### ISSUE TITLE
Problem with log rotation 'monthly'

### ISSUE THREAD

**Issue by fhemberger** [hapijs/good-file#63]
I added good-file as reporter to a hapi v8 project with the following configuration:

```
reporters: [
    {
        reporter: require('good-file'),
        events: { response: '*' },
        config: {
            path   : './log/',
            prefix : 'access',
            rotate : 'monthly'
        }
    }
]
```

As soon as I start the server, it creates 8986 zero-byte log files and the server crashes (ENFILE: file table overflow). Using 'daily' as rotate setting seems to work fine.

**Comment by Marsup** [comment]
Related to #62.

**Comment by Marsup** [comment]
And duplicate of #61.
