### ISSUE TITLE
good-file creating new log file on bounce - why? 

### ISSUE THREAD

**Issue by mattkime** [hapijs/good-file#77]
I see the note in the readme about creating new logs on bounce but i was curious if you could say more about the collision concern. I'm unfamiliar with it and this runs counter to my experience logging on other systems.

**Comment by arb** [comment]
Simplicity for one. Trying to "pick up" where the last file was would add a lot of annoying complexity. For another, I wanted to avoid the situation where you start good-file, log a few things, and then restart everything and have that original file over written.

**Comment by mattkime** [comment]
it sounds like you're describing problems generally solved by http://www.linuxcommand.org/man_pages/logrotate8.html

**Comment by arb** [comment]
I am exactly describing problems solved by log rotate :smile: This is what is used internally at Walmart and they don't use the rotate option; they use logrotate to handle it as you've suggested.

**Comment by mattkime** [comment]
bffft, i just needed to read the docs more closely. need to configure with a string for the file path instead of an object.

thanks @arb
