### ISSUE TITLE
Example of using  stream-rotate in Hapi

### ISSUE THREAD

**Issue by codetrash** [hapijs/good-file#82]
Could please give an example of how to use  stream-rotate inside Hapi JS ?

**Comment by arb** [comment]
You would just include it as a stream option into good with the correct `args` required for the constructor. I don't really know much about stream-rotate other than it does file rotation.

**Comment by tom2strobl** [comment]
This is open-source and, therefore, no one ever is really allowed to grumble. But what is a use case where I want file-logging without rotation? The latest update seems like a weird step back for me.

`stream-rotate` afaik does not work out of the box:
```
{
  module: 'stream-rotate',
  args: [{
    path: './logs',
    name: 'log.txt',
    ts_format: 'YYYY-MM-dd',
    size: 10000
  }]
}
```
throws:
```
Error: Error in opsFile. stream-rotate must create a stream that has a pipe function.
```
but rotating-file-stream works fine:
```
{
  module: 'good-squeeze',
  name: 'Squeeze',
  args: [{ops: '*'}]
}, {
  module: 'good-squeeze',
  name: 'SafeJson',
  args: [{seperator: '\n'}]
}, {
  module: 'rotating-file-stream',
  name: 'RotatingFileStream',
  args: ['logs.log', {
    path: './logs/', // base path
    size: '10M', // rotate every 10 MegaBytes written
    interval: '1d', // rotate daily
    compress: true // compress rotated files
  }]
}
```
**NOTE: setting interval to `30d` doesn't work and `compress: 'gzip'` didn't work for me either.**

While I absolutely do appreciate all the hard work you guys put into the hapi-ecosystem, this last update broke something for me that worked perfectly fine before and required trial and error and lost time with no benefit (for me). It might allow for new flexibility for some, but I suppose most people want the same 3-4 things from a logger, log-rotation into a file being at the very top for a lot of people.

Feel free to include the above rotating-file-stream snippet in the readme if there are other people wanting file rotation back.

Knowing that this comment basically reads like a rant, I want to emphasize again that I'm very, very, very thankful and appreciate all the hard work that went into the hapi-ecosystem 🙏 🙇 ❤️

**Comment by arb** [comment]
As I said above, I really can't speak for either of those write streams; they were just two I found that looked like they would fit the bill. I have no affiliation or experience using either of them; they just looked like streams that supported some kind of rotation. They already existed, so writing yet *ANOTHER* npm module that does the same thing as existing ones was not appealing to me at all.

Sorry if this seems like a step back to you. In my, and many other opinion, file rotation shouldn't be done at the Node layer in the first place. Also, I wanted people to use whatever streams they wanted to use, not ones written against some special interface.

Now that I looked at the code again, I see that `stream-rotate` doesn't really implement a write stream, so I'll remove it from the docs.

As with every major release, there is bound to be some hiccups. I am genuinely interested in documentation updates to help smooth out those hiccups; so please feel free to contribute where you think documentation is lacking.

**Comment by alphatan** [comment]
The example shown by @tom2strobl doesn't work here.

Error message:

        Error: Error in file. rotating-file-stream must be a constructor function.

Versions:

        Node: 6.2.2
        hapi: 13.4.1
        rotating-file-stream: 1.0.5

BTW, It really hurts without log rotating.

**Comment by arb** [comment]
@alphatan If you show your configuration, I could tell you what maybe going wrong. That is an error coming from good and my guess is your configuration isn't correct.

As far as it really hurting without log rotation, please see my response above.

**Comment by alphatan** [comment]
@arb Thanks in advance.

The configuration is as followed:

```javascript
        server.register(
            {
                "register" : Good,
                "options" : {
                    "ops" : {
                        "interval" : 1000
                    }
                    ,"reporters" : {
                        "console" : [
                            {
                                "module" : "good-squeeze"
                                ,"name" : "Squeeze"
                                ,"args" : [
                                    { "log" : "*"
                                      ,"response" : "*"
                                    }
                                ]
                            }
                            ,{
                                "module" : "good-console"
                            }
                            ,"stdout"
                        ]
                        ,"file" : [
                            {
                                "module" : "good-squeeze"
                                ,"name" : "Squeeze"
                                ,"args" : [{"ops" : "*"}]
                            }
                            ,{
                                "module" : "good-squeeze"
                                ,"name" : "SafeJson"
                            }
                            ,{
                                "module" : "rotating-file-stream"
                                ,"name" : "RotatingFileStream"
                                ,"args" : [
                                    "nodejs-web.log"
                                    ,{
                                        "path" : Path.join(APPJS_DIR_NAME, "logs")
                                        ,"size" : "10K"
                                        ,"interval" : "1d"
                                        ,"compress" : true
                                    }
                                ]
                            }
                        ]
                   }
                }
            }, function (err) {
                if (err) {
                    throw err; // something bad happened loading the plugin
                }

                server.start(function(){
                    for(let cn of server.connections){
                        server.log("info", "Server listening at: " + cn.info.uri);
                    }
                });
            }
        );
```

**Comment by arb** [comment]
Remove `name: "RotatingFileStream"`. You only need that if the module you are requiring exports more than a constructor function.

**Comment by alphatan** [comment]
It works! Thanks a lot! @arb
