### ISSUE TITLE
TypeError: Invalid non-string/buffer chunk

### ISSUE THREAD

**Issue by abritinthebay** [hapijs/good-file#85]
As soon as I try to run good/good-file I get this:

`There was a problem (TypeError: Invalid non-string/buffer chunk) in fileReporter and it has been destroyed.`

Nothing gets output to a file at all, ever. I'm not exactly doing anything complex with the config:

```
options: {
			ops: {
				interval: 1000
			},
			reporters: {
				consoleReporter: [{
					module: "good-console",
					args: [{
						format: ""
					}]
				}],
				fileReporter: [{
					module: "good-file",
					args: [`./logs/${process.env.RELEASE_ENV}.log`]
				}]
			}
		}
```

Any ideas?

**Comment by arb** [comment]
First your `consoleReporter` isn't writing to anything, so you're going to run out of memory eventually.
Second, your `fileReporter` is going to be passed an object which is what the error you're seeing is about. You need to use a transform stream before good-file to stringify objects.

**Comment by abritinthebay** [comment]
Ahhh I'm updating from the 5.x version of Good and 6.x works quite differently.

Hence the confusion. Thanks for clearing that up.

**Comment by Zedonboy** [comment]
Am seeing the same error. and the log file is created.
```
`{
    ops : {
      interval : 1000
    },
    
reporters : {
      fileReporter : [{
        module : 'good-file',
        args: ['./log/serverlog.log']
      }]
    }
  },`
```

**Comment by Zedonboy** [comment]
@arb Actually Glue gave me this error, when its initializing plugins for the server.
But as for turning object to string. i will, to that in my code, to implememented during runtime.
So how am i going to do it?
